The forces which describe the evolutionary process are among the most powerful and fundamental
forces underlying existence as we know it. These forces can be witnessed accross the lifespan of any
system, and persist from that system's atoms to its highest infinity -- the furthest abstraction
from its base.

Fundamentally all change is a series of arbitrary fluctuations, which either improve or degrade the
holistic structure of a larger system. Typically, however, these changes are so insignificant that,
good or bad, they're smoothed over by the same normalization processes that stabilize that system.

Look at your own body.

The basest components of your body, left to their own devices, fluctuate so wildly that it cannot
even be said whether they exist at a given spacetime coordinate. In fact, until the point that we
*retroactively* impose existence onto those pieces, they both exist and don't exist-- everywhere! Of
course the "weight" of their existence is considerably higher in certain portions of space. And that
imbalance is the foundation of they poorly named atom. Hindsight is 20/20 though right? (We'll come
back to that later.)

So lets look at these atoms. They're nice little packages. They have just the right pattern to
persist their own existence. All their parts create a feedback cycle which ensures that each part
exists because each other part exists. It's gloriously circular.

Now these atoms float around more or less arbitrarily, but sometimes they end up near each
other. Interestingly, as they get closer it becomes clear that they not only persist themselves, but
they seem to radiate some kind of "existence" field. By virtue of an atom's being in a given
location the existence weight of the space around the atom is higher. Over time, disparate atoms
begin coalescing in common locations simply because it's easier for them to exist in those
spots. And the more atoms collect, the easier it gets. Until eventually there is so much in one
place that atom patterns are being forced into each other for lack of anywhere else to go. That is a
star.

Some of these new patterns stick. Like the patterns they came from, they feedback into themselves
and are stable. If they manage to escape being shredded by the chaos that created them and leave the
star, those new elements continue playing this game. Now there are enough differently shaped atoms
around that as they continue their aimless roaming, some of them might stick together, making
molecules. It's not as serious as becoming a new atom, so a lot less force is required and as a
result it tends to happen a lot more often.

Now these molecules have an even greater diversity of shape, and they too combine with one another,
creating ever more numerous and complex patterns. This is the end of the story the vast majority of
the time. And it's not a bad one! Already we have reached a level where the whole prospect of
degrees of existence seems nonsensical. This is a whole new plane of reality! The levels below it
are still real, of course, but they do not directly dictate the behavior of the higher
abstractions. Of course the higher levels are an extension of the lower, but we don't worry about
whether whole molecules exist or not. Remember that they exist because it is the nature of their
organization to permit it.

So what about the unimaginably small portion of those molecules which keep grouping? Now they're
taking on real shapes, which can actually be said to "fit" together in the sense that it's commonly
understood. Wildly different kinds of these shapes, barely recognizable as related come togther
forming larger, more interesting and distinct shapes. Suddenly we're at a level where they can do
something which was impossible before: self-replicate. While the pieces of the levels below them
effectively identical, they were always formed by external forces. But far enough along the
abstraction chain, sufficient complexity is acquired to allow for meta-patterns. Organizations which
contain within themselves their own organization, but in a different encoding. 

Early examples of this, such as RNA, are very closely tied to their meta-pattern. The full physical
structure essentially serves both roles as pattern and meta-pattern. It's analogous to a simple
Quine which does no more than read and copy itself. But as the complexity continues to increase, so
does the capacity for ever-subtler meta-patterns. Taking the RNA, or DNA as the case may now be, and
putting it in a very controlled environment, with a well-defined structure and set of proteins and
chemicals to interact with, significantly narrows the possible decodings. The density of the data
contained can be so much higher, and as a result many many more systems can be described.

Some of these systems are so complex that their meta-patterns describe not only themselves, but
their surroundings, and the actions and interactions of the entities around them. These systems'
models are so powerful that they are able to conjure up entirely new systems and redefine their
reality! We have reached a level so high that the most fundamental principles of its basest
components are being replicated. It is a system which contains an infinite potential which it
collapses, at specific points in space and time, into a definite and real, singular, distinct
reality. A process which we all know as free thought and will. Perhaps we are not merely replicating
the fundamental principles of our bodies, but actually using the very same. The distinction there is
one I will gladly discuss with anyone interested, but it is far outside the scope of this
talk. Perhaps even outside the scope of our lives. Time will tell.

But this!, Ladies and gentlemen. This is why doing things wrong is the right thing to do.

When you're building new understandings, in the beginning you must take in as much information as
you can. Don't worry about whether you think it's right or wrong. Suspend all judgement, the truth
is you're unable to be making it now anyway. And don't worry about overloading yourself. You'll
probably forget most of it regardless. And don't worry about that either. You may not remember it
immediately, but it will come back to you if and when it's relevant. Or it may come back when it is
not, but only then will it be clear that you don't need it.

In fact, it is important to pull in ideas from other disciplines. Don't just focus on the ideas you
think you'll need. Follow their tangents and pull in all that information too. The greater the
diversity of the pieces you start with, the more interesting the results. Again, the point here is
to allow the ideas to coalesce. To gravitate towards each other.

And when they reach a critical mass in your mind, like the fiery inferno within a star, they
will push together and tear apart. You will feel confused. You will feel frustrated, perhaps even
angry at your inability to comprehend your own thoughts. And that is an excellent time to do
something else. Don't force yourself to think about it anymore. Read an easy novel, or play some
music. Take a walk, go for a run, do some gardening, cook a meal. If you're tired, sleep! The point
now is to rest. But not to shutdown. Don't zone out for hours in front of the TV, or lay in bed
nursing your frustration. Light activity will keep your mind working in the background. And then
suddenly, hours, days, maybe weeks later, you'll think about it again. An idea will come to you from
nowhere. It has escaped the star, and is ready to begin its life as the foundation of real
understanding.

Of course, you're going to need a lot more than that one atom. And this process will happen over and
over, but as the number of more complex building blocks grows you will find it takes a lot less
energy to piece them together. They don't require nuclear mind fusion to form... they just need
enough time to interact until they find a way to fit togther. Or perhaps they'll drift apart to some
other ideas which may be more compatible.

This is not an easy process. There will be many false starts, and, more discouraging, promising
leads which may end up being inert-- dead ends. Or ideas which prove to be unstable, thriving in
certain conditions, and breaking down in others. Both of these things can still be useful. Helium
lifts airships; neon makes glowing signs; uranium generates electricity; polonium steers
politics. But you needn't worry about what the use of any of these ideas will be yet. Simply by
having them in your toolbelt, they will find their own applications when the time is right.

So what does it have to do with getting shit done; with just going out and "doing it" rather than
worrying about "doing it right"?


* As we move up in level, the objects become more static while they become more complex
** They cannot change themselves nearly so much
** But quality of what they are is much more varied and interesting
** Plus the number of distinct "types" explodes, which also explodes the diversity of possible interactions


* Hindsight is 20/20
** Analogous to wavefunction collapse
** Now that existence has been imposed on those events, statements about them are trivial






* Small steps are necessary
* Big steps are actually *impossible* without an evolutionary mutation 
** AN ACCIDENTAL, RANDOM OCCURANCE 

* YOu have within you several "thought-action-organisms"
** Some have evolved excellently
*** In These things you are skilled
** Some are considerably less, or not at all evolved
*** In these things you are not
* Your conscious mind is weighted by the relative strengths of these organisms
** The stronger organisms dominate your thought patterns
*** They feedback that you are "only good at them"
*** They demand your time and energy
*** They redirect focus from the weaker organisms
** The weaker organims have grown silent
