The forces which describe the evolutionary process are among the most powerful and fundamental
forces underlying existence as we know it. These forces can be witnessed accross the lifespan of any
system, and persist from that system's atoms to its highest infinity -- the furthest abstraction
from its base.

Fundamentally all change is a series of arbitrary fluctuations, which either improve or degrade the
holistic structure of a larger system. Typically, however, these changes are so insignificant that,
good or bad, they're smoothed over by the same normalization processes that stabilize that system.

Look at your own body.

The basest components of your body, left to their own devices, fluctuate so wildly that it cannot
even be said whether they exist at a given spacetime coordinate. In fact, until the point that we
*retroactively* impose existence onto those pieces, they both exist and don't exist-- everywhere! Of
course the "weight" of their existence is considerably higher in certain portions of space. And that
imbalance is the foundation of the poorly named atom. Hindsight is 20/20 though right? (We'll come
back to that later.)

So lets look at these atoms. They're nice little packages. They have just the right pattern to
persist their own existence. All their parts create a feedback cycle which ensures that each part
exists because each other part exists. It's gloriously circular.

Now these atoms float around more or less arbitrarily, but sometimes they end up near each
other. Interestingly, as they get closer it becomes clear that they not only persist themselves, but
they seem to radiate some kind of "existence" field. By virtue of an atom's being in a given
location the existence weight of the space around the atom is higher. Over time, disparate atoms
begin coalescing in common locations simply because it's easier for them to exist in those
spots. And the more atoms collect, the easier it gets. Until eventually there is so much in one
place that atom patterns are being forced into each other for lack of anywhere else to go. We call
these collections "stars".

Some of these new patterns stick. Like the patterns they came from, they feedback into themselves
and are stable. If they manage to escape being shredded by the chaos that created them and leave the
star, those new elements continue playing this game. Now there are enough differently shaped atoms
around that as they continue their aimless roaming, some of them might stick together, making
molecules. It's not as serious as becoming a new atom, so a lot less force is required and as a
result it tends to happen a lot more often.

Now these molecules have an even greater diversity of shape, and they too combine with one another,
creating ever more numerous and complex patterns. This may be as far as you get, and frankly it's
pretty far. Already we have reached a level where the whole prospect of degrees of existence seems
nonsensical. This is a whole new plane of reality! The levels below it are still real, of course,
but they have almost no direct bearing on the higher abstractions. Remember that the higher levels
exist because it is the very nature of the levels below them to permit it.

?? Maybe extend this up to cell life before wrapping up? I would like to get to consciousness... but
let's not bore the audience too much...

So here we are, lots of molecules. Though this does seem to be the end of the story almost
everywhere, it is clearly not the end here. I'm going to fast forward a bit though; you guys have
probably already figured out where this is going. The importance of this, however, is to illustrate
how the evolutionary process-- arbitrarily making a change and seeing if it sticks-- underlies the
fundamentals of what we commonly think of as evolution.




* As we move up in level, the objects become more static while they become more complex
** They cannot change themselves nearly so much
** But quality of what they are is much more varied and interesting
** Plus the number of distinct "types" explodes, which also explodes the diversity of possible interactions


* Hindsight is 20/20
** Analogous to wavefunction collapse
** Now that existence has been imposed on those events, statements about them are trivial






* Small steps are necessary
* Big steps are actually *impossible* without an evolutionary mutation 
** AN ACCIDENTAL, RANDOM OCCURANCE 

* YOu have within you several "thought-action-organisms"
** Some have evolved excellently
*** In These things you are skilled
** Some are considerably less, or not at all evolved
*** In these things you are not
* Your conscious mind is weighted by the relative strengths of these organisms
** The stronger organisms dominate your thought patterns
*** They feedback that you are "only good at them"
*** They demand your time and energy
*** They redirect focus from the weaker organisms
** The weaker organims have grown silent
